[package]
name = "solsql"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.5.7"
base64ct = "=1.7.3"
solana-program = "3.0.0"
thiserror = "2.0.17"
solana-system-interface = { version = "2.0.0", features = ["bincode"] }
solana-address = "1.0.0"
